### ISSUE TITLE
Aantal mogelijke verbeteringen

### ISSUE THREAD

**Issue by dagwieers** [Opvolger/plugin.video.hanssettings#1]
Na een eerste evaluatie van deze Kodi add-on:

**Interface**
- Ipv '+++Naam+++' kan je deze entries in Bold zetten en als Folder aangeven (in de juiste content view)
- Soms gebruik je term 'landelijk' en soms 'nationaal'
- In **Stream België** staan een aantal zenders tussen Vlaanderen/Wallonië
- Persoonlijk zou ik in het hoofdmenu Vlaanderen en Wallonië al apart oplijsten (ipv. een extra indirectie)
- Na het bekijken van een livestream wordt aangegeven dat je hem al bekeken hebt, dat kan je afzetten
- Sommige kanalen zijn geo-blocked (bv. NPO) en zouden beter zo aangegeven worden
- Sommige kanalen die niet blijken te werken blokkeren Kodi een tijdje
- Met support voor Studio icons zouden sommige kanalen automatisch een logo hebben

**Streams**
- **Stream Jeugd » België** (niet Vlaanderen ?) ontbreekt VRT Ketnet HD, of VRT Ketnet Jr HD
- **Stream Nieuws » Nederland/België** (vreemd dat ze hier samen staan?)
- **Stream Muziek » België** (Radio 1, Stubru en MNM ontbreken?)
- Live streams XITE - HD3, HD4 en HD5 werken niet
  - XITE HD3 werkt wel in **Stream Muziek »  NL + B**, maar niet elders
- Evenaar (docu - België) werkt niet (lijkt [definitief](http://www.eclipstv.be/sites/default/files/2019-05/Persmededeling%20Evenaar.pdf))
- TVO (TV Oost-Vlaanderen) werkt niet
- Euronews werkt niet
- Kanalen van RAI 1 bevatten een typo (talië ipv Italië)

**Ontbrekende streams**
- **Sporza** live stream (zendt niet altijd uit, maar soms wel, e.g. Tour de France, Olympische spelen, WK Voetbal Vrouwen, etc.)
- [Vlaamsparlement.tv](https://vlaamsparlement.tv/) (geen live stream ?)
- [BVN](https://www.bvn.tv/) - [livestream](https://api.new.livestream.com/accounts/27755193/events/8469152/live.m3u8)
- [Q-Music TV](https://qmusic.be/) - [livestream](https://youtu.be/02TvtXuCwt4)
- AVS, RingTV and RTV regional channels (geen live streams ?)

PS Ik heb je add-on toegevoegd aan: https://github.com/pietje666/plugin.video.vrt.nu/wiki/Flemish-TV

**Comment by Opvolger** [comment]
Bedankt voor je commentaar, maar ik gebruik een lijst van ¨Hans Settings", zie https://www.detransponder.nl/downloads-2/kanalenlijsten/.
Hans zet zijn lijst op github, deze lees ik uit. ik kan dus niks aanpassen.

Voorbeeld:
https://github.com/haroo/HansSettings/blob/master/e2_hanssettings_19e_23e/userbouquet.stream_nl_nationaal.tv

**Comment by dagwieers** [comment]
Opvolger, dat dacht ik al, maar misschien kan er samengewerkt worden zodat er een wisselwerking is?
