### ISSUE TITLE
Download streams van github

### ISSUE THREAD

**Issue by peno64** [Opvolger/plugin.video.hanssettings#2]
Telkens als ik navigeer van de ene stream lijst naar de andere lijst wordt de lijst van streams van github opgehaald. Dat is wel storend. Moet dat echt telkens gebeuren? Hij doet dat trouwens ook telkens ik de addin start.

Dit op kodi leia 18.2 op raspberry pi

**Comment by Opvolger** [comment]
Deze lijst staat online. na 24 uur haalt hij alles weer opnieuw op. binnen de 24 uur cached hij alles lokaal.

**Comment by peno64** [comment]
Dat is nu net mijn punt. Hij wacht geen 24 uur maar doet dat constant bij het navigeren doorheen de addon...

**Comment by peno64** [comment]
Ik heb de reden gevonden. Ligt niet aan uw plugin maar aan de plugin EZ Maintenance Plus, legen cache. Deze verwijdert teveel files uit de temp folder waardoor de Common Plugin Cache niet meer werkte en daardoor ging hij telkens opnieuw de streams ophalen.
Ik sluit deze issue daarom af.
