### ISSUE TITLE
wert niet meer

### ISSUE THREAD

**Issue by james1882** [Opvolger/plugin.video.hanssettings#3]
komt er nog een update van deze addon

**Comment by Opvolger** [comment]
ik zie het nu ook. het lijkt een fout in de lijst te zijn.
Zal hier binnenkort naar kijken

**Comment by Opvolger** [comment]
als je 2.2.3 download, werkt alles weer.

**Comment by freja57** [comment]
Bas, na het installleren van 2.2.3 werken de meeste NPO-kanalen niet meer. Zover ik kan zien doen alle buitenlandse kanalen en bijv. BVN en Qmusic het wel weet, maar niks van NPO.

**Comment by Opvolger** [comment]
NPO heeft de stream "beveiligd". Hierdoor werken veel koppelingen met NPO niet meer.
Deze stream lijst is niet van mij, maar van Hans. zijn lijst geef ik weer in ijn addon. dus ik kan hier niks aan doen.
