### ISSUE TITLE
Kodi 19 matrix

### ISSUE THREAD

**Issue by Dominiquedb** [Opvolger/plugin.video.hanssettings#5]
I was wondering if there are any plans to get this addon working in kodi 19 matrix. I just switched over and this is the only addon not working for me from the list of add-ons I use.

Whether you make it 19 compatible or not, I would like to thank you for providing me with this addon, I have enjoyed using for quite some time now.

**Comment by Opvolger** [comment]
i will look at it, thought i had already done this (working for Matrix / Python3) this may not be the case any more.

Will create a virtual machine with Matrix :)

**Comment by Opvolger** [comment]
fixxed in 2.2.4 release.
