### ISSUE TITLE
The add-on does not update the list any more

### ISSUE THREAD

**Issue by ErikBrown2** [Opvolger/plugin.video.hanssettings#7]
It appears that the add-on is not getting updated stream info any more. When I start up the add-on, it shows the usual activity of reading the files. But several of the streams are not working any more while the latest online Hans listings are correct. 

Since a few months Hans had changed the filename format of what he calls the VLC file:

https://www.detransponder.nl/wp-content/uploads/2022/03/202203.m3u8.zip

so that it includes the day. The format used to be YYYYMM.m3u8 but it was changed to YYYYMMDD.m3u8. But that change is now reversed and the filename format is as it was before. But the add-on still does not update the list so it appears that the add-on is using other files. Can you please have a look at this?

**Comment by Opvolger** [comment]
Hoi Erik,

Zoals ik al in een mail aan je beantwoord heb, laat de oplossing nog even opzich wachten.

Groeten Bas.

**Comment by Opvolger** [comment]
Opgelost
