### ISSUE TITLE
The addon stopped working

### ISSUE THREAD

**Issue by ErikBrown2** [Opvolger/plugin.video.hanssettings#8]
When you start the addon, it appears not to download the list. It also does not give an error message. I am using version 2.2.8

![Screenshot 2022-06-12 220847](https://user-images.githubusercontent.com/32511867/173251523-d6b56f9c-47ca-4337-8107-fe383b8da867.jpg)

**Comment by Opvolger** [comment]
The repo where I get the streams is closed by github "DMCA takedown notice for Opvolger/kanalenlijst_hans_sync". A link to Canada was taken down.

https://github.com/github/dmca/blob/master/2022/06/2022-06-06-corus.md

So no links anymore. try to make something else.

**Comment by Opvolger** [comment]
Changed the code, it is working again.

**Comment by ErikBrown2** [comment]
Very nice!!! It works indeed again. The long wait was worth it. 

I think that your add-on is very useful especially now due to the situation in Ukraine. It will help people in countries with restricted news access to still find some uncoloured news sources.

Thanks
