### ISSUE TITLE
Israel Sport channels

### ISSUE THREAD

**Issue by Garyh11** [Opvolger/plugin.video.hanssettings#9]
Hey de Israëlische sport zenders zijn er niet meer
"Met de nieuwste update zijjn de Israelische sportzenders verdwenen. Waarom? Dit werkte prima voor mij"

**Comment by Opvolger** [comment]
Ik beheer de lijst van zenders niet, alleen de plugin om de lijst welke door de satellietclub onderhouden wordt weergeven in Kodi. Ik kan hier dus niks aan veranderen
